# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        name: Check for files larger than 5 MB
        args: [ "--maxkb=5120" ]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
    -   id: detect-secrets
        exclude: (.env.example|.env.test|^.github/workflows/|.cruft.json|aws_architecture)

  - repo: local
    hooks:
    -   id: detect-ip
        name: Detect IP addresses
        entry: '^(?!0\.0\.0\.0$)(?!127\.0\.0\.1$)\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'
        language: pygrep
        exclude: '^static/|\.lock'
        files: .
        
  - repo: local
    hooks:
    -   id: detect-aws-account
        name: Detect AWS account numbers
        language: pygrep
        entry: ':\d{12}:'

  - repo: local
    hooks:
      - id: eslint
        name: ESLint
        entry: >
          bash -c '
            cd frontend;
            npm install;
            for file in "$@"; do
              # remove the leading "frontend/" from each path
              rel="${file#frontend/}";
              npx eslint "$rel" --fix || exit $?
            done
          ' _
        language: system
        pass_filenames: true
        files: ^frontend/.*\.(?:js|jsx|ts|tsx)$
