services:

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: astro
    ports:
      - "8081:8081"
    env_file:
      - .env
    networks:
      - gov-ai-client-network
    depends_on:
      - postgres

  postgres:
    image: pgvector/pgvector:pg17
    ports:
      - '5433:5432'
    environment:
    - POSTGRES_USER=root # because root will execute the init script
    - POSTGRES_PASSWORD=postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
      - ./scripts/postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      retries: 10
      start_period: 60s
      start_interval: 1s
    networks:
      - gov-ai-client-network

networks:
  gov-ai-client-network:
    driver: bridge

volumes:
  postgres_data:
